export const PUZZLES = [
  {
    id: "p1",
    size: 5,
    rows: ["FLAME", "ON#AT", "RISKY", "IN#BE", "STORM"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "FLAME", clue: "Olympic torch feature" },
      { no: 2, row: 1, col: 0, len: 2, answer: "ON",    clue: "Switch setting when active" },
      { no: 3, row: 1, col: 3, len: 2, answer: "AT",    clue: "The @ sign, informally" },
      { no: 4, row: 2, col: 0, len: 5, answer: "RISKY", clue: "Like a high-wire act" },
      { no: 5, row: 3, col: 0, len: 2, answer: "IN",    clue: "Fashionable, informally" },
      { no: 6, row: 3, col: 3, len: 2, answer: "BE",    clue: "Hamlet's infinitive" },
      { no: 7, row: 4, col: 0, len: 5, answer: "STORM", clue: "Brainstorm half" },
    ],
  },
  {
    id: "p2",
    size: 5,
    rows: ["GRAPE", "OR#IT", "UNITY", "UP#IS", "DANCE"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "GRAPE", clue: "Pre-raisin state" },
      { no: 2, row: 1, col: 0, len: 2, answer: "OR",    clue: "Gold, in heraldry" },
      { no: 3, row: 1, col: 3, len: 2, answer: "IT",    clue: "Stephen King clown, briefly" },
      { no: 4, row: 2, col: 0, len: 5, answer: "UNITY", clue: "Popular indie game engine" },
      { no: 5, row: 3, col: 0, len: 2, answer: "UP",    clue: "Pixar film with a flying house" },
      { no: 6, row: 3, col: 3, len: 2, answer: "IS",    clue: "\"What ___ love?\"" },
      { no: 7, row: 4, col: 0, len: 5, answer: "DANCE", clue: "Fred Astaire's specialty" },
    ],
  },
  {
    id: "p3",
    size: 5,
    rows: ["BLAZE", "GO#IF", "NOTCH", "DO#WE", "SWIFT"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "BLAZE", clue: "Trail marker on a tree" },
      { no: 2, row: 1, col: 0, len: 2, answer: "GO",    clue: "Ancient board game with black and white stones" },
      { no: 3, row: 1, col: 3, len: 2, answer: "IF",    clue: "Kipling's famous poem" },
      { no: 4, row: 2, col: 0, len: 5, answer: "NOTCH", clue: "A cut above? No, just one" },
      { no: 5, row: 3, col: 0, len: 2, answer: "DO",    clue: "Scale's opener" },
      { no: 6, row: 3, col: 3, len: 2, answer: "WE",    clue: "Royal self-reference" },
      { no: 7, row: 4, col: 0, len: 5, answer: "SWIFT", clue: "Taylor or a barn bird" },
    ],
  },
  {
    id: "p4",
    size: 5,
    rows: ["SNOWY", "SO#BY", "PIXEL", "ME#OR", "VIVID"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "SNOWY", clue: "Tintin's terrier" },
      { no: 2, row: 1, col: 0, len: 2, answer: "SO",    clue: "___ far, so good" },
      { no: 3, row: 1, col: 3, len: 2, answer: "BY",    clue: "Author credit preposition" },
      { no: 4, row: 2, col: 0, len: 5, answer: "PIXEL", clue: "Megapixel's millionth" },
      { no: 5, row: 3, col: 0, len: 2, answer: "ME",    clue: "Narcissist's favourite topic" },
      { no: 6, row: 3, col: 3, len: 2, answer: "OR",    clue: "Either's partner" },
      { no: 7, row: 4, col: 0, len: 5, answer: "VIVID", clue: "Like a fever dream" },
    ],
  },
  {
    id: "p5",
    size: 5,
    rows: ["CLAMP", "AS#NO", "YACHT", "HE#TO", "KNELT"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "CLAMP", clue: "Woodworker's grip" },
      { no: 2, row: 1, col: 0, len: 2, answer: "AS",    clue: "While, in verse" },
      { no: 3, row: 1, col: 3, len: 2, answer: "NO",    clue: "Dr. ___, first Bond villain" },
      { no: 4, row: 2, col: 0, len: 5, answer: "YACHT", clue: "America's Cup vessel" },
      { no: 5, row: 3, col: 0, len: 2, answer: "HE",    clue: "Fifth Hebrew letter" },
      { no: 6, row: 3, col: 3, len: 2, answer: "TO",    clue: "\"___ be or not ___ be\"" },
      { no: 7, row: 4, col: 0, len: 5, answer: "KNELT", clue: "Popped the question, perhaps" },
    ],
  },
];
