export const PUZZLES = [
  {
    id: "p1",
    size: 5,
    rows: ["FLAME", "ON#AT", "RISKY", "IN#BE", "STORM"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "FLAME", clue: "Tongue of fire" },
      { no: 2, row: 1, col: 0, len: 2, answer: "ON",    clue: "Active, not off" },
      { no: 3, row: 1, col: 3, len: 2, answer: "AT",    clue: "Located here" },
      { no: 4, row: 2, col: 0, len: 5, answer: "RISKY", clue: "Dangerous to attempt" },
      { no: 5, row: 3, col: 0, len: 2, answer: "IN",    clue: "Inside" },
      { no: 6, row: 3, col: 3, len: 2, answer: "BE",    clue: "Exist" },
      { no: 7, row: 4, col: 0, len: 5, answer: "STORM", clue: "Thunder bringer" },
    ],
  },
  {
    id: "p2",
    size: 5,
    rows: ["GRAPE", "OR#IT", "UNITY", "UP#IS", "DANCE"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "GRAPE", clue: "Purple vine fruit" },
      { no: 2, row: 1, col: 0, len: 2, answer: "OR",    clue: "Either / ___" },
      { no: 3, row: 1, col: 3, len: 2, answer: "IT",    clue: "Neither he nor she" },
      { no: 4, row: 2, col: 0, len: 5, answer: "UNITY", clue: "Togetherness" },
      { no: 5, row: 3, col: 0, len: 2, answer: "UP",    clue: "Skyward" },
      { no: 6, row: 3, col: 3, len: 2, answer: "IS",    clue: "Exists right now" },
      { no: 7, row: 4, col: 0, len: 5, answer: "DANCE", clue: "Boogie!" },
    ],
  },
  {
    id: "p3",
    size: 5,
    rows: ["BLAZE", "GO#IF", "NOTCH", "DO#WE", "SWIFT"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "BLAZE", clue: "Raging inferno" },
      { no: 2, row: 1, col: 0, len: 2, answer: "GO",    clue: "Proceed!" },
      { no: 3, row: 1, col: 3, len: 2, answer: "IF",    clue: "On the condition that" },
      { no: 4, row: 2, col: 0, len: 5, answer: "NOTCH", clue: "V-shaped cut" },
      { no: 5, row: 3, col: 0, len: 2, answer: "DO",    clue: "Perform" },
      { no: 6, row: 3, col: 3, len: 2, answer: "WE",    clue: "You and I" },
      { no: 7, row: 4, col: 0, len: 5, answer: "SWIFT", clue: "Very fast" },
    ],
  },
  {
    id: "p4",
    size: 5,
    rows: ["SNOWY", "SO#BY", "PIXEL", "ME#OR", "VIVID"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "SNOWY", clue: "Like a blizzard day" },
      { no: 2, row: 1, col: 0, len: 2, answer: "SO",    clue: "Therefore" },
      { no: 3, row: 1, col: 3, len: 2, answer: "BY",    clue: "Next to" },
      { no: 4, row: 2, col: 0, len: 5, answer: "PIXEL", clue: "Screen's tiniest dot" },
      { no: 5, row: 3, col: 0, len: 2, answer: "ME",    clue: "First-person object" },
      { no: 6, row: 3, col: 3, len: 2, answer: "OR",    clue: "Alternative" },
      { no: 7, row: 4, col: 0, len: 5, answer: "VIVID", clue: "Intensely bright" },
    ],
  },
  {
    id: "p5",
    size: 5,
    rows: ["CLAMP", "AS#NO", "YACHT", "HE#TO", "KNELT"],
    across: [
      { no: 1, row: 0, col: 0, len: 5, answer: "CLAMP", clue: "Grip firmly" },
      { no: 2, row: 1, col: 0, len: 2, answer: "AS",    clue: "In the role of" },
      { no: 3, row: 1, col: 3, len: 2, answer: "NO",    clue: "Refusal" },
      { no: 4, row: 2, col: 0, len: 5, answer: "YACHT", clue: "Luxury sailing boat" },
      { no: 5, row: 3, col: 0, len: 2, answer: "HE",    clue: "Male pronoun" },
      { no: 6, row: 3, col: 3, len: 2, answer: "TO",    clue: "Toward" },
      { no: 7, row: 4, col: 0, len: 5, answer: "KNELT", clue: "Got down on one knee" },
    ],
  },
];
